apiVersion: apps/v1    # Ensure the correct apiVersion
kind: Deployment
metadata:
  name: go-web-app
  labels:              # Corrected 'lables' to 'labels'
    app: go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:       # Corrected 'matchLables' to 'matchLabels'
      app: go-web-app
  template:
    metadata:
      labels:          # Corrected 'lables' to 'labels'
        app: go-web-app
    spec:
      containers:
      - name: go-web-app
        image: dhana1993/go-web-app:latest
        ports:
        - containerPort: 8080
